#!/usr/bin/env bash
#
# install.sh — install syck + syck-hunt into ~/bin and update shell rc files.
#
# Idempotent: safe to run multiple times.  Skips work that's already done.
# Cross-shell: updates both .zshrc and .bashrc if they exist.
#
# Usage:
#   ./install.sh              # install
#   ./install.sh --uninstall  # undo the install
#   ./install.sh --prefix DIR # install into a different directory

set -euo pipefail

# ── locate scripts ───────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SYCK_PY="$SCRIPT_DIR/syck.py"
SYCK_HUNT_PY="$SCRIPT_DIR/syck-hunt.py"

if [[ ! -f "$SYCK_PY" || ! -f "$SYCK_HUNT_PY" ]]; then
    echo "error: run this from the repo root (could not find syck.py / syck-hunt.py)" >&2
    exit 1
fi

# Self-heal CRLF if the file was checked out on Windows
if file "$0" 2>/dev/null | grep -qi "CRLF"; then
    sed -i 's/\r$//' "$0"
fi

# ── options ──────────────────────────────────────────────────────
PREFIX="${HOME}/bin"
ACTION="install"
while [[ $# -gt 0 ]]; do
    case "$1" in
        --uninstall) ACTION="uninstall" ;;
        --prefix)    PREFIX="$2"; shift ;;
        --prefix=*)  PREFIX="${1#*=}" ;;
        -h|--help)
            sed -n '2,12p' "$0"
            exit 0
            ;;
        *) echo "unknown arg: $1" >&2; exit 2 ;;
    esac
    shift
done

# ── uninstall ───────────────────────────────────────────────────
if [[ "$ACTION" == "uninstall" ]]; then
    echo "Uninstalling from $PREFIX …"
    rm -f "$PREFIX/syck" "$PREFIX/syck-hunt"
    echo "[+] removed shims"
    echo "[i] you may want to manually clean the PATH lines from your shell rc files:"
    echo "    $HOME/.zshrc  $HOME/.bashrc"
    exit 0
fi

# ── install ─────────────────────────────────────────────────────
echo "Installing into $PREFIX …"
mkdir -p "$PREFIX"

# ── default config ─────────────────────────────────────────────
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/syck"
CONFIG_FILE="$CONFIG_DIR/config.json"
mkdir -p "$CONFIG_DIR"

if [[ -f "$CONFIG_FILE" ]]; then
    echo "[·] $CONFIG_FILE already exists — keeping it"
else
    cat > "$CONFIG_FILE" <<'CONFIG_EOF'
{
    "workers": 10,
    "max-file-size": "5M",
    "decode-base64": true,
    "progress": true,
    "redact": false,
    "no-color": false
}
CONFIG_EOF
    echo "[+] created $CONFIG_FILE"
fi

write_shim() {
    local target="$1"
    local script="$2"
    cat > "$target" <<EOF
#!/usr/bin/env bash
# Auto-generated by syck installer on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
exec python3 "$script" "\$@"
EOF
    chmod +x "$target"
}

write_shim "$PREFIX/syck"      "$SYCK_PY"
write_shim "$PREFIX/syck-hunt" "$SYCK_HUNT_PY"
echo "[+] shims:"
echo "    $PREFIX/syck"
echo "    $PREFIX/syck-hunt"

# ── update shell rc files ───────────────────────────────────────
# We patch THREE files so the PATH change is visible from every shell
# invocation:
#
#   .zshenv     — sourced by EVERY zsh (interactive + non-interactive)
#   .profile    — sourced by login shells (bash, sh, often zsh)
#   .zshrc      — sourced by INTERACTIVE zsh (for completions, prompts)
#   .bashrc     — sourced by INTERACTIVE bash (for completions, prompts)
#
# The .zshenv + .profile pair is what makes the tools visible to
# non-interactive shells (e.g. `wsl -d kali -- bash -c "syck"`,
# `subprocess.run(["syck"])`, CI runs).  Without those, the user hits
# the classic "tool not found" gotcha.

MARKER="# >>> syck installer >>>"
END_MARKER="# <<< syck installer <<<"
PATH_BLOCK=$(cat <<EOF

$MARKER
# Added by syck installer — keep this block intact so re-runs are idempotent
case ":\$PATH:" in
    *":$PREFIX:"*) ;;
    *) export PATH="$PREFIX:\$PATH" ;;
esac
$END_MARKER
EOF
)

patch_file() {
    local f="$1"
    # Create the file if missing
    [[ -e "$f" ]] || : > "$f"
    if grep -qF "$MARKER" "$f" 2>/dev/null; then
        echo "[·] $f already patched"
        return
    fi
    printf '%s\n' "$PATH_BLOCK" >> "$f"
    echo "[+] updated $f"
}

# Always patch the env-wide files (these matter for non-interactive shells)
patch_file "$HOME/.zshenv"
patch_file "$HOME/.profile"

# Also patch the interactive shell files if they exist
[[ -f "$HOME/.zshrc"  ]] && patch_file "$HOME/.zshrc"
[[ -f "$HOME/.bashrc" ]] && patch_file "$HOME/.bashrc"

# If no interactive rc file exists, create one for the user's login shell
if [[ ! -f "$HOME/.zshrc" && ! -f "$HOME/.bashrc" ]]; then
    case "${SHELL:-}" in
        */zsh) patch_file "$HOME/.zshrc" ;;
        *)     patch_file "$HOME/.bashrc" ;;
    esac
fi

# ── final report ────────────────────────────────────────────────
echo
echo "Done."
echo
echo "Patched shell files (re-source to apply in the current shell):"
echo "  source ~/.zshenv      # for non-interactive shells"
echo "  source ~/.zshrc       # for interactive zsh (prompts, completions)"
echo "  source ~/.profile     # for login shells (bash, sh)"
echo "  source ~/.bashrc      # for interactive bash"
echo
echo "Verify with (works from a non-interactive shell too):"
echo "  which syck       → $PREFIX/syck"
echo "  which syck-hunt  → $PREFIX/syck-hunt"
echo "  syck --help      → 'usage: syck'"
